language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 'node'
  - '6'
before_install:
  - npm i -g npm@~4.0.0
before_script:
  - npm prune
script:
  - npm run coverage
  - codecov
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
